FROM tomcat:8.5-jre8

MAINTAINER "Chin-Hung Chen <chinhung101@gmail.com>"

ADD context.xml /usr/local/tomcat/webapps/manager/META-INF/
ADD settings.xml /usr/local/tomcat/conf/
ADD tomcat-users.xml /usr/local/tomcat/conf/